service: everymundo-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
